import os
import typing as t
from io import TextIOWrapper
from datetime import datetime

from .definitions import (
    EXPRESSION_BASE_NAME,
    STATEMENT_BASE_NAME,
    EXPRESSION_TYPES,
    STATEMENT_TYPES,
)
from .types import NodeDefinitionMapping, NodeDefinitions

__all__ = ["main"]

BASE_ABSTRACT_CLASS: str = """
@dataclass
class {CLASS_NAME}(ABC):
    @abstractmethod
    def accept[T](self, visitor: '{CLASS_NAME}Visitor[T]') -> T:
        pass

    def __post_init__(self) -> None:
        if self.__class__ == {CLASS_NAME}:
            raise TypeError("Cannot instantiate abstract class.")
"""

HEAD: t.Final[str] = f"""# Autogenerated via tools/generate_ast.py at {datetime.now()}
import typing as t
from dataclasses import dataclass
from abc import ABC, abstractmethod

from .types import Token

__all__ = {[type for type in ["Expression", "Statement", *EXPRESSION_TYPES.keys(), *STATEMENT_TYPES.keys()]]}


{BASE_ABSTRACT_CLASS.format(CLASS_NAME=EXPRESSION_BASE_NAME)}

{BASE_ABSTRACT_CLASS.format(CLASS_NAME=STATEMENT_BASE_NAME)}

"""


def define_ast(
    file: TextIOWrapper, base_name: str, types: NodeDefinitionMapping
) -> None:
    define_visitor(file, base_name, types)

    for class_name, properties in types.items():
        define_type(
            file,
            base_name,
            class_name,
            properties,
        )


def define_type(
    file: TextIOWrapper,
    base_name: str,
    class_name: str,
    field_type_pairs: NodeDefinitions,
) -> None:
    file.write(f"@dataclass(slots=True)\nclass {class_name}({base_name}):\n")

    for field_type_pair in field_type_pairs:
        field_type, field_name = field_type_pair["type"], field_type_pair["name"]
        file.write(f"\t{field_name}: {field_type}\n")

    file.write(
        f'\n\t@t.override\n\tdef accept[T](self, visitor: "{base_name}Visitor[T]") -> T:\n'
    )
    file.write(
        f"\t\treturn visitor.visit_{class_name.lower()}_{base_name.lower()}(self)\n"
    )
    file.write("\n\n")


def define_visitor(
    file: TextIOWrapper, base_name: str, types: NodeDefinitionMapping
) -> None:
    file.write(f"class {base_name}Visitor[T](t.Protocol):\n\t")

    for class_name, _ in types.items():
        l_class_name, l_base_name = class_name.lower(), base_name.lower()
        file.write(
            f'def visit_{l_class_name}_{l_base_name}(self, {l_base_name}: "{class_name}") -> T:\n\t\tpass\n\n\t'
        )

    file.write("\n")


def main() -> int:
    output_dir: str = "gustav/ast.py"
    print(f"Generating AST, output => {output_dir}")

    global HEAD

    file = open(output_dir, "wt")
    file.write(HEAD)

    try:
        define_ast(file, EXPRESSION_BASE_NAME, EXPRESSION_TYPES)
        define_ast(file, STATEMENT_BASE_NAME, STATEMENT_TYPES)
    except Exception as exc:
        raise exc
        # return os.EX_DATAERR
    else:
        return os.EX_OK
    finally:
        file.close()
