import os
import logging
import typing as t
from io import TextIOWrapper
from datetime import datetime

from .definitions import EXPRESSION_TYPES, STATEMENT_TYPES

logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s | %(funcName)s():%(lineno)d] %(message)s",
)
LOG = logging.getLogger(__name__)

__all__ = ("main",)

EXPRESSION_BASE_NAME = "Expression"
STATEMENT_BASE_NAME = "Statement"

INIT_IMPORTS = """from .statement import Statement, StatementVisitor
from .expression import Expression, ExpressionVisitor

__all__ = ("Expression", "Statement", "ExpressionVisitor", "StatementVisitor")
"""

BASE_ABSTRACT_CLASS = """
@dataclass(frozen=True, slots=True, eq=False)
class {CLASS_NAME}(ABC):
    @abstractmethod
    def accept[T](self, visitor: '{CLASS_NAME}Visitor[T]') -> T:
        pass
"""

HEAD = f"# Autogenerated via tools/ast_generator module at {datetime.now()}\n"


class NodeDefinition(t.TypedDict):
    type: str
    name: str


NodeDefinitions = list[NodeDefinition]
NodeDefinitionMapping = dict[str, NodeDefinitions]


def as_node_definition_mapping(types: dict[str, str]) -> NodeDefinitionMapping:
    result: NodeDefinitionMapping = dict()

    for node, definition in types.items():
        fields: list[str] = list(map(str.strip, definition.split(",")))

        result[node] = [
            {"type": field_type, "name": field_name}
            for field_name, field_type in map(
                lambda field: list(map(str.strip, field.split(":"))), fields
            )
        ]

    return result


def define_ast(
    file: TextIOWrapper, base_name: str, types: NodeDefinitionMapping
) -> None:
    IMPORTS = (
        HEAD
        + "import typing as t\nfrom dataclasses import dataclass\nfrom abc import ABC, abstractmethod\n\n"
        + "from gustav.token import Token\n"
    )
    if base_name == "Statement":
        IMPORTS += "from gustav.ast import expression as E\n"

    file.write(IMPORTS)
    file.write(
        f"__all__ = {tuple(T for T in [*types.keys(), base_name, f'{base_name}Visitor'])}\n\n"
    )
    file.write(BASE_ABSTRACT_CLASS.format(CLASS_NAME=base_name) + "\n")

    define_visitor(file, base_name, types)

    for class_name, properties in types.items():
        define_type(
            file,
            base_name,
            class_name,
            properties,
        )


def define_type(
    file: TextIOWrapper,
    base_name: str,
    class_name: str,
    field_type_pairs: NodeDefinitions,
) -> None:
    file.write(
        f"@dataclass(frozen=True, slots=True, eq=False)\nclass {class_name}({base_name}):\n"
    )

    for field_type_pair in field_type_pairs:
        field_type, field_name = field_type_pair["type"], field_type_pair["name"]
        file.write(f"\t{field_name}: {field_type}\n")

    file.write(
        f'\n\t@t.override\n\tdef accept[T](self, visitor: "{base_name}Visitor[T]") -> T:\n'
    )
    file.write(
        f"\t\treturn visitor.visit_{class_name.lower()}_{base_name.lower()}(self)\n"
    )
    file.write("\n\n")


def define_visitor(
    file: TextIOWrapper, base_name: str, types: NodeDefinitionMapping
) -> None:
    LOG.debug(f"Defining visitor for {base_name}")

    file.write(f"class {base_name}Visitor[T](t.Protocol):\n\t")

    for class_name, _ in types.items():
        l_class_name, l_base_name = class_name.lower(), base_name.lower()
        file.write(
            f'def visit_{l_class_name}_{l_base_name}(self, {l_base_name}: "{class_name}") -> T:\n\t\tpass\n\n\t'
        )

    file.write("\n")


def main() -> int:
    LOG.debug("Generate AST - Starting")

    os.makedirs("gustav/ast", exist_ok=True)

    try:
        with open("gustav/ast/__init__.py", "wt") as file:
            LOG.debug("Writing imports for __init__.py")
            file.write(INIT_IMPORTS)

        for base_name, types in (
            (EXPRESSION_BASE_NAME, as_node_definition_mapping(EXPRESSION_TYPES)),
            (STATEMENT_BASE_NAME, as_node_definition_mapping(STATEMENT_TYPES)),
        ):
            with open(f"gustav/ast/{base_name.lower()}.py", "wt") as file:
                LOG.debug(
                    f"Defining ast for {base_name} with types => {tuple(types.keys())}"
                )
                define_ast(file, base_name, types)

    except Exception as exc:
        raise exc
        # return os.EX_DATAERR
    else:
        LOG.debug("Generate AST - Finished")
        return os.EX_OK
    finally:
        file.close()
