# Autogenerated via tools/ast_generator module at 2025-08-11 03:10:59.611218
import typing as t
from dataclasses import dataclass
from abc import ABC, abstractmethod

__all__ = ("Expression", "Statement")


@dataclass(frozen=True, slots=True, eq=False)
class Expression(ABC):
    @abstractmethod
    def accept(self, visitor: t.Any) -> t.Any:
        pass  # pragma: no cover


@dataclass(frozen=True, slots=True, eq=False)
class Statement(ABC):
    @abstractmethod
    def accept(self, visitor: t.Any) -> t.Any:
        pass  # pragma: no cover
