# Autogenerated via tools/ast_generator module at 2025-08-01 23:22:26.154466
import typing as t
from dataclasses import dataclass

from gustav.token import Token
from gustav.ast.base import Expression, Statement

__all__ = (
    "Assign",
    "Binary",
    "Ternary",
    "Call",
    "Get",
    "Set",
    "This",
    "Groupping",
    "Literal",
    "Logical",
    "Variable",
    "Unary",
    "Super",
    "Lambda",
    "ExpressionVisitor",
    "Expression",
)


class ExpressionVisitor[T](t.Protocol):
    def visit_assign_expression(self, expression: "Assign") -> T:
        pass  # pragma: no cover

    def visit_binary_expression(self, expression: "Binary") -> T:
        pass  # pragma: no cover

    def visit_ternary_expression(self, expression: "Ternary") -> T:
        pass  # pragma: no cover

    def visit_call_expression(self, expression: "Call") -> T:
        pass  # pragma: no cover

    def visit_get_expression(self, expression: "Get") -> T:
        pass  # pragma: no cover

    def visit_set_expression(self, expression: "Set") -> T:
        pass  # pragma: no cover

    def visit_this_expression(self, expression: "This") -> T:
        pass  # pragma: no cover

    def visit_groupping_expression(self, expression: "Groupping") -> T:
        pass  # pragma: no cover

    def visit_literal_expression(self, expression: "Literal") -> T:
        pass  # pragma: no cover

    def visit_logical_expression(self, expression: "Logical") -> T:
        pass  # pragma: no cover

    def visit_variable_expression(self, expression: "Variable") -> T:
        pass  # pragma: no cover

    def visit_unary_expression(self, expression: "Unary") -> T:
        pass  # pragma: no cover

    def visit_super_expression(self, expression: "Super") -> T:
        pass  # pragma: no cover

    def visit_lambda_expression(self, expression: "Lambda") -> T:
        pass  # pragma: no cover


@dataclass(frozen=True, slots=True, eq=False)
class Assign(Expression):
    name: Token
    value: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_assign_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Binary(Expression):
    left: Expression
    operator: Token
    right: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_binary_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Ternary(Expression):
    condition: Expression
    then_branch: Expression
    else_branch: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_ternary_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Call(Expression):
    callee: Expression
    paren: Token
    arguments: list[Expression]

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_call_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Get(Expression):
    object: Expression
    name: Token

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_get_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Set(Expression):
    object: Expression
    name: Token
    value: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_set_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class This(Expression):
    keyword: Token

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_this_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Groupping(Expression):
    expression: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_groupping_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Literal(Expression):
    value: object

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_literal_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Logical(Expression):
    left: Expression
    operator: Token
    right: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_logical_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Variable(Expression):
    name: Token

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_variable_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Unary(Expression):
    operator: Token
    right: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_unary_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Super(Expression):
    keyword: Token
    method: Token

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_super_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Lambda(Expression):
    params: list[Token]
    body: list[Statement]

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_lambda_expression(self)
