# Autogenerated via tools/ast_generator module at 2025-07-18 04:07:21.264769
import typing as t
from dataclasses import dataclass
from abc import ABC, abstractmethod

from gustav.token import Token

__all__ = (
    "Assign",
    "Binary",
    "Ternary",
    "Call",
    "Get",
    "Set",
    "Groupping",
    "Literal",
    "Logical",
    "Variable",
    "Unary",
    "Expression",
    "ExpressionVisitor",
)


@dataclass(frozen=True, slots=True, eq=False)
class Expression(ABC):
    @abstractmethod
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        pass

    def __post_init__(self) -> None:
        if self.__class__ == Expression:
            raise TypeError("Cannot instantiate abstract class.")


class ExpressionVisitor[T](t.Protocol):
    def visit_assign_expression(self, expression: "Assign") -> T:
        pass

    def visit_binary_expression(self, expression: "Binary") -> T:
        pass

    def visit_ternary_expression(self, expression: "Ternary") -> T:
        pass

    def visit_call_expression(self, expression: "Call") -> T:
        pass

    def visit_get_expression(self, expression: "Get") -> T:
        pass

    def visit_set_expression(self, expression: "Set") -> T:
        pass

    def visit_groupping_expression(self, expression: "Groupping") -> T:
        pass

    def visit_literal_expression(self, expression: "Literal") -> T:
        pass

    def visit_logical_expression(self, expression: "Logical") -> T:
        pass

    def visit_variable_expression(self, expression: "Variable") -> T:
        pass

    def visit_unary_expression(self, expression: "Unary") -> T:
        pass


@dataclass(frozen=True, slots=True, eq=False)
class Assign(Expression):
    name: Token
    value: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_assign_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Binary(Expression):
    left: Expression
    operator: Token
    right: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_binary_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Ternary(Expression):
    condition: Expression
    then_branch: Expression
    else_branch: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_ternary_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Call(Expression):
    callee: Expression
    paren: Token
    arguments: list[Expression]

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_call_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Get(Expression):
    object: Expression
    name: Token

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_get_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Set(Expression):
    object: Expression
    name: Token
    value: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_set_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Groupping(Expression):
    expression: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_groupping_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Literal(Expression):
    value: object

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_literal_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Logical(Expression):
    left: Expression
    operator: Token
    right: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_logical_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Variable(Expression):
    name: Token

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_variable_expression(self)


@dataclass(frozen=True, slots=True, eq=False)
class Unary(Expression):
    operator: Token
    right: Expression

    @t.override
    def accept[T](self, visitor: "ExpressionVisitor[T]") -> T:
        return visitor.visit_unary_expression(self)
