# Autogenerated via tools/ast_generator module at 2025-08-11 03:10:59.611218
import typing as t
from dataclasses import dataclass

from gustav.token import Token
from gustav.ast.base import Expression, Statement
from gustav.ast import expression as E

__all__ = (
    "Block",
    "Class",
    "Expr",
    "If",
    "Function",
    "Print",
    "Return",
    "While",
    "Var",
    "For",
    "Break",
    "Continue",
    "StatementVisitor",
    "Statement",
)


class StatementVisitor[T](t.Protocol):
    def visit_block_statement(self, statement: "Block") -> T:
        pass  # pragma: no cover

    def visit_class_statement(self, statement: "Class") -> T:
        pass  # pragma: no cover

    def visit_expr_statement(self, statement: "Expr") -> T:
        pass  # pragma: no cover

    def visit_if_statement(self, statement: "If") -> T:
        pass  # pragma: no cover

    def visit_function_statement(self, statement: "Function") -> T:
        pass  # pragma: no cover

    def visit_print_statement(self, statement: "Print") -> T:
        pass  # pragma: no cover

    def visit_return_statement(self, statement: "Return") -> T:
        pass  # pragma: no cover

    def visit_while_statement(self, statement: "While") -> T:
        pass  # pragma: no cover

    def visit_var_statement(self, statement: "Var") -> T:
        pass  # pragma: no cover

    def visit_for_statement(self, statement: "For") -> T:
        pass  # pragma: no cover

    def visit_break_statement(self, statement: "Break") -> T:
        pass  # pragma: no cover

    def visit_continue_statement(self, statement: "Continue") -> T:
        pass  # pragma: no cover


@dataclass(frozen=True, slots=True, eq=False)
class Block(Statement):
    statements: list[Statement]

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_block_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Class(Statement):
    name: Token
    superclass: E.Variable | None
    methods: list["Function"]

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_class_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Expr(Statement):
    expression: Expression

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_expr_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class If(Statement):
    condition: Expression
    then_branch: Statement
    else_branch: Statement | None

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_if_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Function(Statement):
    name: Token
    params: list[Token]
    body: list[Statement]

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_function_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Print(Statement):
    expression: Expression

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_print_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Return(Statement):
    keyword: Token
    value: Expression | None

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_return_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class While(Statement):
    condition: Expression
    body: Statement

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_while_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Var(Statement):
    name: Token
    initializer: Expression

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_var_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class For(Statement):
    initializer: Var | Expr | None
    condition: Expression | E.Literal
    increment: Expr | None
    body: Statement

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_for_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Break(Statement):
    keyword: Token

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_break_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Continue(Statement):
    keyword: Token

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_continue_statement(self)
