# Autogenerated via tools/ast_generator module at 2025-07-19 01:28:05.606976
import typing as t
from dataclasses import dataclass
from abc import ABC, abstractmethod

from gustav.token import Token
from gustav.ast.expression import Expression

__all__ = (
    "Block",
    "Class",
    "Expr",
    "If",
    "Function",
    "Print",
    "Return",
    "While",
    "Var",
    "Statement",
    "StatementVisitor",
)


@dataclass(frozen=True, slots=True, eq=False)
class Statement(ABC):
    @abstractmethod
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        pass

    def __post_init__(self) -> None:
        if self.__class__ == Statement:
            raise TypeError("Cannot instantiate abstract class.")


class StatementVisitor[T](t.Protocol):
    def visit_block_statement(self, statement: "Block") -> T:
        pass

    def visit_class_statement(self, statement: "Class") -> T:
        pass

    def visit_expr_statement(self, statement: "Expr") -> T:
        pass

    def visit_if_statement(self, statement: "If") -> T:
        pass

    def visit_function_statement(self, statement: "Function") -> T:
        pass

    def visit_print_statement(self, statement: "Print") -> T:
        pass

    def visit_return_statement(self, statement: "Return") -> T:
        pass

    def visit_while_statement(self, statement: "While") -> T:
        pass

    def visit_var_statement(self, statement: "Var") -> T:
        pass


@dataclass(frozen=True, slots=True, eq=False)
class Block(Statement):
    statements: list[Statement]

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_block_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Class(Statement):
    name: Token
    methods: list["Function"]

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_class_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Expr(Statement):
    expression: Expression

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_expr_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class If(Statement):
    condition: Expression
    then_branch: Statement
    else_branch: Statement | None

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_if_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Function(Statement):
    name: Token
    params: list[Token]
    body: list[Statement]

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_function_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Print(Statement):
    expression: Expression

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_print_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Return(Statement):
    keyword: Token
    value: Expression | None

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_return_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class While(Statement):
    condition: Expression
    body: Statement

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_while_statement(self)


@dataclass(frozen=True, slots=True, eq=False)
class Var(Statement):
    name: Token
    initializer: Expression | None

    @t.override
    def accept[T](self, visitor: "StatementVisitor[T]") -> T:
        return visitor.visit_var_statement(self)
