# Autogenerated at 2025-06-03 00:20:47.898378
from abc import ABC
from dataclasses import dataclass

from ._token import Token


@dataclass
class Expression(ABC):
    def __post_init__(self) -> None:
        if self.__class__ == Expression:
            raise TypeError("Cannot instantiate abstract class.")


@dataclass(slots=True)
class Binary(Expression):
    left: Expression
    right: Expression


@dataclass(slots=True)
class Groupping(Expression):
    expression: Expression


@dataclass(slots=True)
class Literal(Expression):
    value: object


@dataclass(slots=True)
class Unary(Expression):
    operator: Token
    right: Expression
