# Autogenerated at 2025-06-09 22:39:07.410790
import typing as t
from dataclasses import dataclass
from abc import ABC, abstractmethod

from .types import Token

__all__ = ["Expression", "Binary", "Groupping", "Literal", "Unary"]


@dataclass
class Expression(ABC):
    @abstractmethod
    def accept[T](self, visitor: "Visitor[T]") -> T:
        pass

    def __post_init__(self) -> None:
        if self.__class__ == Expression:
            raise TypeError("Cannot instantiate abstract class.")


class Visitor[T](t.Protocol):
    def visit_binary_expression(self, expression: "Binary") -> T:
        pass

    def visit_groupping_expression(self, expression: "Groupping") -> T:
        pass

    def visit_literal_expression(self, expression: "Literal") -> T:
        pass

    def visit_unary_expression(self, expression: "Unary") -> T:
        pass


@dataclass(slots=True)
class Binary(Expression):
    left: Expression
    operator: Token
    right: Expression

    @t.override
    def accept[T](self, visitor: "Visitor[T]") -> T:
        return visitor.visit_binary_expression(self)


@dataclass(slots=True)
class Groupping(Expression):
    expression: Expression

    @t.override
    def accept[T](self, visitor: "Visitor[T]") -> T:
        return visitor.visit_groupping_expression(self)


@dataclass(slots=True)
class Literal(Expression):
    value: object

    @t.override
    def accept[T](self, visitor: "Visitor[T]") -> T:
        return visitor.visit_literal_expression(self)


@dataclass(slots=True)
class Unary(Expression):
    operator: Token
    right: Expression

    @t.override
    def accept[T](self, visitor: "Visitor[T]") -> T:
        return visitor.visit_unary_expression(self)
