import os
import typing as t
from io import TextIOWrapper
from datetime import datetime


BASE_NAME: t.Final[str] = "Expression"


class NodeDefinition(t.TypedDict):
    type: str
    name: str


NodeDefinitions = list[NodeDefinition]
NodeDefinitionMapping = dict[str, NodeDefinitions]


TYPES: NodeDefinitionMapping = {
    "Binary": [
        {"type": BASE_NAME, "name": "left"},
        {"type": "Token", "name": "operator"},
        {"type": BASE_NAME, "name": "right"},
    ],
    "Groupping": [
        {"type": BASE_NAME, "name": "expression"},
    ],
    "Literal": [
        {"type": "object", "name": "value"},
    ],
    "Unary": [
        {"type": "Token", "name": "operator"},
        {"type": BASE_NAME, "name": "right"},
    ],
}


HEAD: t.Final[str] = f"""# Autogenerated at {datetime.now()}
import typing as t
from dataclasses import dataclass
from abc import ABC, abstractmethod

from .types import Token

__all__ = {[type for type in ["Expression", *TYPES.keys()]]}


@dataclass
class {BASE_NAME}(ABC):
    @abstractmethod
    def accept[T](self, visitor: 'Visitor[T]') -> T:
        pass

    def __post_init__(self) -> None:
        if self.__class__ == {BASE_NAME}:
            raise TypeError("Cannot instantiate abstract class.")


"""


def define_ast(output_dir: str, base_name: str, types: NodeDefinitionMapping) -> None:
    global HEAD

    file = open(output_dir, "wt")

    file.write(HEAD)

    define_visitor(file, base_name, types)

    for class_name, properties in types.items():
        define_type(
            file,
            base_name,
            class_name,
            properties,
        )

    file.close()


def define_type(
    file: TextIOWrapper,
    base_name: str,
    class_name: str,
    field_type_pairs: NodeDefinitions,
) -> None:
    file.write(f"@dataclass(slots=True)\nclass {class_name}({base_name}):\n")

    for field_type_pair in field_type_pairs:
        field_type, field_name = field_type_pair["type"], field_type_pair["name"]
        file.write(f"\t{field_name}: {field_type}\n")

    file.write('\n\t@t.override\n\tdef accept[T](self, visitor: "Visitor[T]") -> T:\n')
    file.write(
        f"\t\treturn visitor.visit_{class_name.lower()}_{base_name.lower()}(self)\n"
    )
    file.write("\n\n")


def define_visitor(
    file: TextIOWrapper, base_name: str, types: NodeDefinitionMapping
) -> None:
    file.write("class Visitor[T](t.Protocol):\n\t")

    for class_name, _ in types.items():
        l_class_name, l_base_name = class_name.lower(), base_name.lower()
        file.write(
            f'def visit_{l_class_name}_{l_base_name}(self, {l_base_name}: "{class_name}") -> T:\n\t\tpass\n\n\t'
        )

    file.write("\n")


def main() -> int:
    output_dir: str = "gustav/ast.py"
    print(f"Generating AST, output => {output_dir}")

    try:
        define_ast(output_dir, BASE_NAME, TYPES)
    except Exception as exc:
        print(f"Error: {exc}")
        return os.EX_DATAERR
    else:
        return os.EX_OK


if __name__ == "__main__":
    raise SystemExit(main())
