name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v6

            - name: List files in the repository
              run: |
                  ls ${{ github.workspace }}

            - name: Install Clang
              run: |
                  clang --version
